// Generated from the Figma file (scripts/design): word groups the design keeps on
// one line with non-breaking spaces in its headings. The CMS copy uses plain spaces,
// so headings re-apply these to wrap where the design does.
export const FIGMA_KEEP_TOGETHER = [
  "of distinctive management",
  "Your two-year leadership",
  "Hire practitioners. Not",
  "Corporate interactions.",
  "Development Programmes.",
  "Officially recognised.",
  "Cross-committee forum.",
  "Anti-Ragging Helpline.",
  "Detailed outcomes per",
  "the Director's desk.",
  "& accreditations you",
  "Why Simarthan exists",
  "the Entrepreneurship",
  "run something great.",
  "Upcoming programmes.",
  "Four commitments we",
  "committees actually",
  "B-Road, Churchgate,",
  "RUN SOMETHINGGREAT.",
  "Mumbai's financial",
  "Email vs. WhatsApp",
  "Defining moments.",
  "· faculty-guided.",
  "Visiting faculty.",
  "current-year PDFs",
  "just attend. They",
  "Direct department",
  "Every week. Every",
  "Common questions.",
  "SIMSREE newsroom.",
  "something beyond",
  "Character first.",
  "the curriculum.\"",
  "Curated industry",
  "from Churchgate",
  "Just announced.",
  "built over four",
  "Our programmes.",
  "cohort actually",
  "Stay connected.",
  "companies. Pick",
  "graduates land.",
  "Research areas.",
  "your programme.",
  "MMS admissions.",
  "PhD admissions.",
  "something? Tell",
  "companies hire",
  "for character-",
  "An invitation.",
  "Recent honours",
  "Across India's",
  "Alumni Portal.",
  "Simarthan does",
  "with Simarthan",
  "to admissions.",
  "to engage with",
  "the leadership",
  "Join Placement",
  "Committee does",
  "Join Marketing",
  "custom MDP for",
  "5,000+ alumni",
  "in management",
  "the Director.",
  "punches above",
  "for yourself.",
  "the Placement",
  "cohort landed",
  "from SIMSREE.",
  "you'll learn.",
  "2026-27 cycle",
  "Core faculty.",
  "& Affidavits.",
  "students win.",
  "Who's running",
  "the Corporate",
  "Relation does",
  "Welcome home.",
  "your calendar",
  "We>WE'RE TRUE",
  "from India's",
  "A privilege.",
  "spaces, each",
  "SIMSREE made",
  "your chapter",
  "the Gateway.",
  "· WhatsApp ·",
  "for breadth.",
  "Apex student",
  "Join Hrudaya",
  "· 50-college",
  "see details.",
  "goes beyond",
  "comes next.",
  "Our people.",
  "24 featured",
  "12 services",
  "the 2024-26",
  "your hiring",
  "to SIMSREE.",
  "is elected.",
  "We'll route",
  "at SIMSREE.",
  "· 2023–2025",
  "that slaps.",
  "Events Hub.",
  "on campus.",
  "& Mission.",
  "worth your",
  "sector. We",
  "· 2025-26.",
  "can apply.",
  "each cycle",
  "your M.Sc.",
  "the Alumni",
  "the Course",
  "the Events",
  "One campus",
  "to begin?",
  "over four",
  "in touch.",
  "- Chinese",
  "13 active",
  "the SIMAA",
  "to bring.",
  "Cell does",
  "their own",
  "to visit",
  "we stand",
  "degree -",
  "All four",
  "your MMS",
  "your MMM",
  "your MFM",
  "your PhD",
  "Join SSR",
  "by date,",
  "by type.",
  "All past",
  "by those",
  "who set",
  "like at",
  "in. Pay",
  "· fully",
  "ways to",
  "· 18–19",
  "me and",
  "to MMS",
  "a path",
  "MDPs ·",
  "to GS",
  "· one"
];
