export default {
  name: 'alumniPage',
  title: 'Illustrious Alumni Page',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Hero'},
    {name: 'stats', title: 'Stats'},
    {name: 'hallOfFame', title: 'Hall of Fame Intro'},
    {name: 'directory', title: 'Directory Intro'},
    {name: 'testimonial', title: 'Testimonial'},
    {name: 'employers', title: 'Employers Intro'},
    {name: 'cta', title: 'Stay Connected'},
  ],
  fields: [
    {name: 'heroEyebrow', title: 'Eyebrow', type: 'string', group: 'hero'},
    {name: 'heroTitle', title: 'Title', type: 'string', group: 'hero'},
    {name: 'heroDescription', title: 'Description', type: 'text', rows: 3, group: 'hero'},
    {name: 'heroImage', title: 'Hero image', type: 'image', options: {hotspot: true}, group: 'hero'},
    {name: 'heroPrimaryCtaLabel', title: 'Primary CTA label', type: 'string', group: 'hero'},
    {name: 'heroPrimaryCtaUrl', title: 'Primary CTA URL', type: 'string', group: 'hero'},
    {name: 'heroSecondaryCtaLabel', title: 'Secondary CTA label', type: 'string', group: 'hero'},
    {name: 'heroSecondaryCtaUrl', title: 'Secondary CTA URL', type: 'string', group: 'hero'},
    {
      name: 'stats',
      title: 'Stat cards',
      type: 'array',
      group: 'stats',
      of: [
        {
          type: 'object',
          fields: [
            {name: 'label', title: 'Label', type: 'string'},
            {name: 'value', title: 'Value', type: 'string'},
            {name: 'dark', title: 'Dark (navy) background?', type: 'boolean', initialValue: false},
          ],
          preview: {select: {title: 'value', subtitle: 'label'}},
        },
      ],
    },
    {name: 'hofEyebrow', title: 'Eyebrow', type: 'string', group: 'hallOfFame'},
    {name: 'hofTitle', title: 'Title', type: 'string', group: 'hallOfFame'},
    {name: 'hofTitleHighlight', title: 'Title highlight', type: 'string', group: 'hallOfFame'},
    {name: 'hofSubtitle', title: 'Subtitle', type: 'text', rows: 2, group: 'hallOfFame'},
    {name: 'directoryEyebrow', title: 'Eyebrow', type: 'string', group: 'directory'},
    {name: 'directoryTitle', title: 'Title', description: 'The profile count is prefixed automatically', type: 'string', group: 'directory'},
    {name: 'directorySubtitle', title: 'Subtitle', type: 'string', group: 'directory'},
    {name: 'testimonialEyebrow', title: 'Eyebrow', type: 'string', group: 'testimonial'},
    {name: 'testimonialTitle', title: 'Title', type: 'string', group: 'testimonial'},
    {name: 'testimonialTitleHighlight', title: 'Title highlight', type: 'string', group: 'testimonial'},
    {name: 'employersEyebrow', title: 'Eyebrow', type: 'string', group: 'employers'},
    {name: 'employersTitle', title: 'Title', type: 'string', group: 'employers'},
    {name: 'employersTitleHighlight', title: 'Title highlight', type: 'string', group: 'employers'},
    {name: 'employersSubtitle', title: 'Subtitle', type: 'string', group: 'employers'},
    {name: 'ctaEyebrow', title: 'Eyebrow', type: 'string', group: 'cta'},
    {name: 'ctaTitle', title: 'Title', type: 'string', group: 'cta'},
    {name: 'ctaTitleHighlight', title: 'Title highlight', type: 'string', group: 'cta'},
    {name: 'ctaSubtitle', title: 'Subtitle', type: 'text', rows: 2, group: 'cta'},
    {
      name: 'ctaCards',
      title: 'Cards',
      type: 'array',
      group: 'cta',
      of: [
        {
          type: 'object',
          fields: [
            {name: 'title', title: 'Title', type: 'string'},
            {name: 'description', title: 'Description', type: 'text', rows: 2},
            {name: 'linkLabel', title: 'Link label', type: 'string'},
            {name: 'linkUrl', title: 'Link URL', type: 'string'},
          ],
          preview: {select: {title: 'title', subtitle: 'linkLabel'}},
        },
      ],
    },
  ],
  preview: {prepare() { return {title: 'Illustrious Alumni Page'} }},
}
